language: php

php:
  - '7.3'
  - '7.4'
  - nightly

matrix:
    allow_failures:
      - php: nightly

before_install:
  - nvm install 12

# Clones WordPress and configures our testing environment.
before_script:
  - composer install --no-interaction
  - npm install

script:
  - composer build
  - composer lint-all
  - composer test

after_script:
  # Push coverage off to Codecov
  - bash <(curl -s https://codecov.io/bash)
